// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAbr2yIso9-xmdKvp07ZA6V32-qpPufA',
    appId: '1:888111753989:web:235c4d63ac7853200f656c',
    messagingSenderId: '888111753989',
    projectId: 'route-movies',
    authDomain: 'route-movies.firebaseapp.com',
    storageBucket: 'route-movies.appspot.com',
    measurementId: 'G-58HJHB93WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClaz0L1eZtb6MU38kTefbCtAelqBOooTk',
    appId: '1:888111753989:android:f4f15e2d303316540f656c',
    messagingSenderId: '888111753989',
    projectId: 'route-movies',
    storageBucket: 'route-movies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKremOTDwo5E7zHC96pajz85umKupHcg',
    appId: '1:888111753989:ios:7b714b80aba084ee0f656c',
    messagingSenderId: '888111753989',
    projectId: 'route-movies',
    storageBucket: 'route-movies.appspot.com',
    iosBundleId: 'com.example.moviesAppRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWKremOTDwo5E7zHC96pajz85umKupHcg',
    appId: '1:888111753989:ios:7b714b80aba084ee0f656c',
    messagingSenderId: '888111753989',
    projectId: 'route-movies',
    storageBucket: 'route-movies.appspot.com',
    iosBundleId: 'com.example.moviesAppRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnAbr2yIso9-xmdKvp07ZA6V32-qpPufA',
    appId: '1:888111753989:web:e8fdd1b55bab5f0b0f656c',
    messagingSenderId: '888111753989',
    projectId: 'route-movies',
    authDomain: 'route-movies.firebaseapp.com',
    storageBucket: 'route-movies.appspot.com',
    measurementId: 'G-FYLW6XF3MY',
  );
}
